webtalk_init -webtalk_dir C:/Users/Aaron/Desktop/PYARQUI/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/ESCOMIPS_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul  2 15:29:40 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "279393ff-b360-459f-9331-e71028bc2a2d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "466b599ef89f437aac17b9003f595855" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "44" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2012 R2 or Windows 8.1" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Pentium(R) CPU  J2900  @ 2.41GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2417 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5920_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4268371231 -regid "" -xml C:/Users/Aaron/Desktop/PYARQUI/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/ESCOMIPS_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Aaron/Desktop/PYARQUI/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/ESCOMIPS_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Aaron/Desktop/PYARQUI/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/ESCOMIPS_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
